Frontend/user signup
christian-japan-devs/catholicviet-jp pull request #21
Opened 2021-05-10 14:21 UTC by DangHoangGeo

@sandangel  review お願いいたします。

2021-05-10 14:44 UTC, sandangel requested changes
e check lại nha

2021-05-10 14:44 UTC, sandangel commented on frontend/src/components/auth/Login.tsx
>  const LoginForm = (props: any) => {
cấm xài any. 😌😌😌

2021-05-10 14:44 UTC, sandangel commented on frontend/src/components/auth/Login.tsx
> +              error={errors.username ? true : false}
`!!errors.username` là dc

2021-05-10 14:44 UTC, sandangel commented on frontend/src/components/auth/Login.tsx
> +              helperText={errors.password1}
sao lại là password1?

2021-05-10 14:44 UTC, sandangel commented on frontend/src/components/auth/Signup.tsx
> -import React from 'react';
file chưa format

2021-05-10 14:44 UTC, sandangel commented on frontend/src/components/auth/Signup.tsx
> +const mapStateToProps = (state:any) => ({
cấm any

2021-05-10 14:44 UTC, sandangel commented on frontend/src/components/other/Copyright.tsx
> +      <Link color="inherit" href="https://vietcatholicjp.com/">
có mua domain chưa

2021-05-10 14:44 UTC, sandangel commented on frontend/src/store/types/auth.d.ts
> +export type FormData = {
types để trong file .ts bình thường là dc, ko cần .d.ts

2021-05-10 15:23 UTC, DangHoangGeo commented on frontend/src/components/auth/Login.tsx
>  const LoginForm = (props: any) => {
Thế thì hơi nhiều đấy, =D
Do em chưa biết khai báo kiểu như thế nào cho phù hợp.
Ví dụ a coi trong cái actions -> cauth hàm authLogin chỗ dispatch. chỗ đấy ko để any thì làm thế nào a?????

2021-05-10 15:24 UTC, DangHoangGeo commented on frontend/src/components/other/Copyright.tsx
> +      <Link color="inherit" href="https://vietcatholicjp.com/">
Chưa đâu a,

2021-05-10 15:26 UTC, DangHoangGeo commented on frontend/src/store/types/auth.d.ts
> +export type FormData = {
Ok a

2021-05-10 15:26 UTC, DangHoangGeo commented on frontend/src/components/auth/Signup.tsx
> +const mapStateToProps = (state:any) => ({
Rồi để em tìm cách khai báo kiểu hết

2021-05-10 15:27 UTC, DangHoangGeo commented on frontend/src/components/auth/Signup.tsx
> -import React from 'react';
Dạ

2021-05-12 03:42 UTC, DangHoangGeo commented
@sandangel 
Em xoá mấy cái bữa thử đi, 
cấu trúc lại folder, a coi cấu trúc như thế đã ổn chưa.

2021-05-12 03:45 UTC, DangHoangGeo commented
@sandangel 
Em tính để cái này https://github.com/isaachinman/next-i18next vào
tiện thể a đã sửa next.js vào chưa. 
em nghĩ làm xong mấy cái nền cần thiết trước đã rồi dev tiếp.

2021-05-12 12:01 UTC, sandangel commented
a thấy cái cấu trúc folder mới phức tạp hơn ko cần thiết. cố gắng để flat, ko nên nest folder.

2021-05-12 12:02 UTC, sandangel commented
mấy cái any e chưa sửa kìa

2021-05-12 17:11 UTC, DangHoangGeo commented
@sandangel em để folder đơn giản hơn rồi đây,
mấy cái any em mới đổi được một số thôi. để unknow ko chạy được.
mà ép kiểu mấy cái chưa được. để từ từ em sửa tiếp.

2021-05-13 01:44 UTC, sandangel commented
cũng ko giống ý a lắm. a pull về sửa lại rùi tạo PR làm mẫu cho.

2021-05-13 11:02 UTC, DangHoangGeo commented
@sandangel giờ em di chuyển code qua bên next có cần cài đặt gì ko anh hay chỉ thêm thư viện còn thiếu thôi
, package.json có cần cài đặt gì ko_

2021-05-13 11:04 UTC, sandangel commented
e add dependencies thiếu thui

2021-05-30 10:00 UTC, closed without merging